// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/ryota0624/go-dev-with-ent/ent/runtime.go

const (
	Version = "v0.10.2-0.20220627115711-84b05c05cd19" // Version of ent codegen.
)
