// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/ryota0624/go-dev-with-ent/ent/runtime.go

const (
	Version = "v0.10.2-0.20220407165443-5dd5acc08d0e"           // Version of ent codegen.
	Sum     = "h1:pyi1r2QHcaiudAGrZpo+nKM89F4r0pHhnuk3nb0ueXM=" // Sum of ent codegen.
)
