// Code generated by ogen, DO NOT EDIT.
package ogent

type CreateUserRes interface {
	createUserRes()
}

type ListUserRes interface {
	listUserRes()
}

type ReadUserRes interface {
	readUserRes()
}

type UpdateUserRes interface {
	updateUserRes()
}
