version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=passward
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    ports:
     - "3000:8080"
    volumes:
      - ../:/go/src
    tty: true
  profefe-collector:
    image: profefe/profefe:latest
    command:
      - -addr=:10100
      - -storage-type=badger
      - -badger.dir=/data
    ports:
      - 10100:10100
